package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	REMOVE_NODE, FOLLOW, LIST_FILES, LIST_FILES_RESPONSE, REMOVE_FILE, REMOVE_FILE_RESPONSE, PENDING, REMOVING_UPDATE,
	TOKEN_REQUEST, SEND_TOKEN
}
